### PR TITLE
Added autosave encounter

### PR DESCRIPTION
**Pull request by Lawrr**
Added autosave encounter suggested in #44 and also removed some redundant lines from LoadUiSettings.

### CODE REVIEW

**Comment by Gl0** [comment]
#44 is not just saving timed out encounter (wich may be done by default, without any setting option), but capture S_DESPAWN_NPC, check entity.isBoss, and auto save if it is true.

**Comment by lunyx** [comment]
GI0 is correct.  Timed out encounters are not being saved with this option and this doesn't change anything from just pressing the save hotkey.

**Comment by Lawrr** [comment]
Ok I understand what Gl0 is saying, but I don't understand what you mean by timed out encounters not being saved with this. This is giving the option to save the timed out encounters so that you don't have to keep pressing the hotkey and won't lose encounters just because you forgot to save it, which is partially what #44 was getting to.

**Comment by lunyx** [comment]
My mistake, Lawrr.  I read that incorrectly.

**Comment by lunyx** [comment]
By the way, I haven't forgotten about this.  I'll be integrating it when I get a chance to make it based on boss death instead.  

Question @Gl0, does S_DESPAWN_NPC occur only when the boss dies or also when you reset the boss by pulling him out of the room?  This could get annoying if that's the case.

**Comment by Gl0** [comment]
If you go too far from boss, so that boss will be out of view range (much farer than needed to reset) - you will receive despawn packet, but there seems to be a flag in it, which is different for mob death (05) and out of view (01). Need to do more tests to be sure.
Use of teleport scroll doesn't trigger despawn packet.

**Comment by Lawrr** [comment]
Fair enough.

**Comment by lunyx** [comment]
Closing this since #71 duplicates it.

**Pull request closed without merging**
