### PR TITLE
raw sockets and UI fixes

### PR DESCRIPTION
**Pull request by Gl0**
Listen on all available interfaces in raw sockets mode
Increase buffer size for raw sockets
Delete IP settings (unneeded)
UI fixes for large monitors/multimonitor configuration

### CODE REVIEW

**Comment by lunyx** [comment]
Can you provide some background information on the UI size?  I have multiple monitors and am running 4k on one of them and haven't experienced any issues.  Any reproducible steps?  I'd like to be able to solve it without referencing an entirely different windows framework.

**Comment by Gl0** [comment]
On my system (2560x1600 + 120dpi windows setting) main window is clipped at nearly 900px
And on another system there are 2 monitors with different resolutions, the small one is secondary, left, and shifted down. The meter started on this monitor open detailed skill window higher than monitor boundary.
Аfter setting Height in CasualMeterWindow.cs to 1600px detailed windows started to appear out of screen even on my system, so I had to implement WindowStartupLocation.CenterScreen by myself.
I'm c# newbie, so I took the first one example from google to get current screen info.

**Comment by Gl0** [comment]
Ups, that was my fault with 1600px, Height there have to be in device-independent pixels, Changed it to 
`Height = SystemParameters.WorkArea.Height;` 
and WindowStartupLocation.CenterScreen started to work well on my system.
But dualmonitor issue still needed windows.forms or some other way to get current screen dimensions

**Comment by lunyx** [comment]
I'll take a closer look at this over the weekend when I have some time.

**Comment by lunyx** [comment]
Is the winforms section supposed to be about trying to center the window manually?  It seems to me that what happens is that CenterWindow tries to locate the center of the screen that the mouse cursor is on.  Is your window still disappearing despite this?

**Comment by Gl0** [comment]
The key is to put window into the boundary of current screen (where the meter window is), left top corner of this screen have non zero coords. So y=0 in independent pixels appears upper than screen boundary.

**Comment by Gl0** [comment]
May be that is windows 7 related issue, try to setup 2 monitors so that left one is secondary with taskbar and have less height than primary, shift left screen down to the center of right screen, put meter window on it and try to open detailed window.

**Comment by Gl0** [comment]
> I think it's because that's what the breakdown height/width are.
yes

**Comment by Gl0** [comment]
keep in mind, that they have to be not in independent pixels in this expression

**Pull request merged**
