### PR TITLE
new features

### PR DESCRIPTION
**Pull request by Gl0**
Add KR and JP support, ninja class, common multilanguage skill & monster database #59 
Add options "Count only bosses" and "Ignore oneshots" #24 
Different modifiers for hotkeys.
Default paste string include damage
Pet skills showing as pet name.
Autoswitch language to fit connected server (for EU servers default is EU-EN)
Language may be changed via config.

Also include latest gothos fixes to skills and monsters databases, updated with new fields.
Opcodes, skills and monster database from https://github.com/neowutran/TeraDpsMeterData

### CODE REVIEW

**Comment by lunyx** [comment]
Wow, looks like you're on a roll with the updates.  I'll review it when I can, probably this weekend.

**Comment by Gl0** [comment]
Most of it was done more than month ago (see my [fork](https://github.com/Gl0/CasualMeter)) and tested by RU community all this time. Recent changes are only multilanguage (was RU only) and switch to xml monster database format.

**Comment by Gl0** [comment]
Seems we can cut off your original skill-overrides, after latest update to extractor all skills that was there should exist in main skilldatabase file.

**Comment by lunyx** [comment]
FYI, I committed fixes for some issues:

- String typed settings were being changed due to converter
- Capitalized skill details
- Removed extra spaces in SkillDetailedName
- Fixed gunner HB bot heal not being deteced

I also removed damage from the default DPS paste string because it's a useless statistic IMO.  The whole point is to measure damage done in a meaningful way, which is DPS.  Percentage contribution already tells how you did overall relative to the rest of the party.

**Comment by Gl0** [comment]
Hm... HB bot heal is the only skill, used by HB, and it shows as heal in skillstats under localized name of bot(HB-7 for NA/EU-EN) without your override.
Damage give the information about when encounter was reset (someone may forget to reset it before boss) how many mobs it contains. May be add total damage for the whole party to the paste string?

**Comment by lunyx** [comment]
Before I added the override, it did not show up at all, though the other hits were showing up (electric bomb).  I reset multiple times and it didn't change anything.

**Comment by Gl0** [comment]
Very strange, verified it right now, it works. 
Electric bomb's owner is player itself, it's s different mechanic.

**Comment by lunyx** [comment]
I'll test it again later.

**Comment by lunyx** [comment]
It does show for me now.  Not sure what could have caused it.

**Comment by Gl0** [comment]
It may be bot casted before you see the caster, so that your meter don't now, who is bot's owner.

**Pull request merged**
