### PR TITLE
Auto save

### PR DESCRIPTION
**Pull request by Gl0**
Auto save encounter on boss death. #44 
Name saved encounter with the name of last dead boss.
Auto save timed out encounter ( https://github.com/lunyx/CasualMeter/pull/68 ).
Auto switch from viewing saved encounter on boss aggro (not sure, whether it need to be configurable).

### CODE REVIEW

**Comment by Gl0** [comment]
Added header to paste string

**Comment by Gl0** [comment]
Not sure what to do with long boss names, causing saved encounter description to be clipped by meter window border/scrollbar. 
May be put it to the end of string, so that clipping does not affect tracker stats.
Or clip name manually to ~20 symbols. 
Or leave it as is now, since the number of bosses with long names is small enough.

**Comment by lunyx** [comment]
I'm thinking we could just make the boss name a tooltip so that it shows up when you mouse over.

**Comment by Gl0** [comment]
May be combination of clipped name and full tooltip? Searching for particular boss in long list only by tooltips is not comfortable.

**Comment by lunyx** [comment]
There's an issue where resetting meter manually after hitting a boss still saves meter using ctrl + del.  Also doesn't work correctly on deso in fihm due to multiple bosses dying.

**Comment by Gl0** [comment]
To fix FIHM tou need only update monster monsters-override.xml to the latest version.

**Pull request merged**
