### PR TITLE
Fix raw sockets IP sniffer and add menu option to select interface.

### PR DESCRIPTION
**Pull request by KaneTW**
This allows CasualMeter to work when using BattlePing etc.

Seems to require Windows Firewall to be turned off.

I haven't tested WinPcap variant.

### CODE REVIEW

**Comment by lunyx** [comment]
Can you provide some more information on how this works? I applied the patch manually to test, but can't get it to work with WTFast.  Windows Firewall is already disabled.  I've already tested 127.0.0.1, as well as the other IP's that show up on the list (my LAN IP and two others which I'm not sure about, but don't seem to be internal since they start with 167).

**Comment by KaneTW** [comment]
You should select the LAN IP in the settings window. Basically packets can appear out of order when using raw sockets, so I moved the removal from the "new connection" collection at the end. 

You're running as admin, right? I forgot to add that -- raw sockets with SIO_RCVALL require admin privileges.

**Comment by lunyx** [comment]
Yes, I'm running as admin.  I figured that one out after running into the exception when trying to create.

**Comment by KaneTW** [comment]
Uh, did you do the resmon thing (add server IP that shows up under resmon to the overrides txt)? Otherwise you could do a breakpoint in TeraSniffer where it handles a packet and see if it receives packets a) at all b) from the server.

**Comment by lunyx** [comment]
Yes, I added that already. I'm debugging it right now, but I suppose that means you're out of leads as well.

**Comment by KaneTW** [comment]
Yeah. It worked with Battleping, so I guess different VPNs or even network setups require different approaches.

**Comment by lunyx** [comment]
It looks like restarting my machine and disabling my virtual network adapters did the trick (did both at the same time).  I'm considering moving the settings out of the UI, however, since it seems that updating it in the UI doesn't actually do anything and will only work after restarting.

**Comment by KaneTW** [comment]
Probably a good idea. I could technically make them restart the sniffer whenever they're changed, but that'd be tomorrow.

**Comment by lunyx** [comment]
No worries. I changed it myself so that it does that.  It now also hides the second option if the first one isn't enabled.

**Comment by lunyx** [comment]
This is done.

**Pull request merged**
